<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=Cp1252">
<title>Insert title here</title>
</head>
<body>

		<h1>Sistema MVC - Usuarios</h1>
                <a href="index.php?rota=usuarios/listar">Listar Usuários</a> |
                <a href="index.php?rota=usuarios/inserir">Inserir Usuários</a>
                <hr>

		<?php require __DIR__ . "/../$caminhoView.phtml"; ?>


</body>
</html>
